// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gtrD5RiA2YjsOIvCX2w_Rg0dC53BYKs',
    appId: '1:332369121877:web:7dc18aef9f5bd123777adc',
    messagingSenderId: '332369121877',
    projectId: 'emergency-tracking-syste-95d0c',
    authDomain: 'emergency-tracking-syste-95d0c.firebaseapp.com',
    storageBucket: 'emergency-tracking-syste-95d0c.firebasestorage.app',
    measurementId: 'G-992EMC4E0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefbqn4ssQtIQlk11eh9yQuiMeD4SrBiY',
    appId: '1:332369121877:android:0d2eb2c6ed2bfe4d777adc',
    messagingSenderId: '332369121877',
    projectId: 'emergency-tracking-syste-95d0c',
    storageBucket: 'emergency-tracking-syste-95d0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9NwnCR9khRDGv0jPwgbSH6Z3p-qHQWS8',
    appId: '1:332369121877:ios:ede6b2018c76fa05777adc',
    messagingSenderId: '332369121877',
    projectId: 'emergency-tracking-syste-95d0c',
    storageBucket: 'emergency-tracking-syste-95d0c.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9NwnCR9khRDGv0jPwgbSH6Z3p-qHQWS8',
    appId: '1:332369121877:ios:ede6b2018c76fa05777adc',
    messagingSenderId: '332369121877',
    projectId: 'emergency-tracking-syste-95d0c',
    storageBucket: 'emergency-tracking-syste-95d0c.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );

}